# Copied from https://github.com/isaac-sim/IsaacLabEvalTasks/blob/main/scripts/config/gr00t/gr00t_joint_space.yaml
# Expected input & output joint names following listed order for groot state/action space
joints:
  left_arm:
    - left_shoulder_pitch_joint
    - left_shoulder_roll_joint
    - left_shoulder_yaw_joint
    - left_elbow_pitch_joint
    - left_wrist_yaw_joint
    - left_wrist_roll_joint
    - left_wrist_pitch_joint
  right_arm:
    - right_shoulder_pitch_joint
    - right_shoulder_roll_joint
    - right_shoulder_yaw_joint
    - right_elbow_pitch_joint
    - right_wrist_yaw_joint
    - right_wrist_roll_joint
    - right_wrist_pitch_joint
  left_hand:
    - L_pinky_proximal_joint
    - L_ring_proximal_joint
    - L_middle_proximal_joint
    - L_index_proximal_joint
    - L_thumb_proximal_yaw_joint
    - L_thumb_proximal_pitch_joint
    # Mimic joints
    # - L_index_intermediate_joint
    # - L_middle_intermediate_joint
    # - L_ring_intermediate_joint
    # - L_pinky_intermediate_joint
    # - L_thumb_distal_joint
  right_hand:
    - R_pinky_proximal_joint
    - R_ring_proximal_joint
    - R_middle_proximal_joint
    - R_index_proximal_joint
    - R_thumb_proximal_yaw_joint
    - R_thumb_proximal_pitch_joint
    # Mimic joints
    # - R_index_intermediate_joint
    # - R_middle_intermediate_joint
    # - R_ring_intermediate_joint
    # - R_pinky_intermediate_joint
    # - R_thumb_distal_joint