# Copied from https://github.com/isaac-sim/IsaacLabEvalTasks/blob/main/scripts/config/gr1/state_joint_space.yaml
# GR1 Robot Joint Configuration used in the state joint space
# Maps joint names to joint indices for easy reference
joints:
  'left_hip_roll_joint': 0
  'right_hip_roll_joint': 1
  'waist_yaw_joint': 2
  'left_hip_yaw_joint': 3
  'right_hip_yaw_joint': 4
  'waist_pitch_joint': 5
  'left_hip_pitch_joint': 6
  'right_hip_pitch_joint': 7
  'waist_roll_joint': 8
  'left_knee_pitch_joint': 9
  'right_knee_pitch_joint': 10
  'head_roll_joint': 11
  'left_shoulder_pitch_joint': 12
  'right_shoulder_pitch_joint': 13
  'left_ankle_pitch_joint': 14
  'right_ankle_pitch_joint': 15
  'head_pitch_joint': 16
  'left_shoulder_roll_joint': 17
  'right_shoulder_roll_joint': 18
  'left_ankle_roll_joint': 19
  'right_ankle_roll_joint': 20
  'head_yaw_joint': 21
  'left_shoulder_yaw_joint': 22
  'right_shoulder_yaw_joint': 23
  'left_elbow_pitch_joint': 24
  'right_elbow_pitch_joint': 25
  'left_wrist_yaw_joint': 26
  'right_wrist_yaw_joint': 27
  'left_wrist_roll_joint': 28
  'right_wrist_roll_joint': 29
  'left_wrist_pitch_joint': 30
  'right_wrist_pitch_joint': 31
  'L_index_proximal_joint': 32
  'L_middle_proximal_joint': 33
  'L_pinky_proximal_joint': 34
  'L_ring_proximal_joint': 35
  'L_thumb_proximal_yaw_joint': 36
  'R_index_proximal_joint': 37
  'R_middle_proximal_joint': 38
  'R_pinky_proximal_joint': 39
  'R_ring_proximal_joint': 40
  'R_thumb_proximal_yaw_joint': 41
  'L_index_intermediate_joint': 42
  'L_middle_intermediate_joint': 43
  'L_pinky_intermediate_joint': 44
  'L_ring_intermediate_joint': 45
  'L_thumb_proximal_pitch_joint': 46
  'R_index_intermediate_joint': 47
  'R_middle_intermediate_joint': 48
  'R_pinky_intermediate_joint': 49
  'R_ring_intermediate_joint': 50
  'R_thumb_proximal_pitch_joint': 51
  'L_thumb_distal_joint': 52
  'R_thumb_distal_joint': 53

total_joints: 54